name: base
channels:
  - conda-forge
dependencies:
  # general
  - pip
  - setuptools

  # jupyterhub/jupyterlab
  - nb_conda_kernels
  - ipython > 7
  - jupyter-server-proxy
  - jupyterlab-git
  - ipywidgets
  - jupyterlab >= 3
  - jupyter_client
  - jupyter_console
  - jupyterhub
  - nodejs >= 10
  - nbconvert
  - nbval

  # dask
  - dask_labextension # requires dask
  - dask==2.14.0
  - distributed==2.14.0
  - dask-gateway==0.6.1
  - pandas

  # viz tools
  - pyviz_comms
  - panel
  - param
  - python-graphviz
  - ipyleaflet

  # testing, docs, linting
  - pytest
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb
  # code formatters
  - autopep8
  - yapf

  # jupyter/lab extensions
  - jupyter-videochat
  - jupyterlab_code_formatter
  - jupytext

  # visual debugging
  - xeus-python

  - pip:
      - jupyter_contrib_nbextensions
